export const CHAIN_IDS = {
  "0x1": "Ethereum Mainnet",
  "0x3": "Ropsten Testnet",
  "0x4": "Rinkeby Testnet",
  "0x5": "Goerli Testnet",
  "0x2a": "Kovan Testnet",
  "0x38": "Binance Smart Chain Mainnet",
  "0x61": "Binance Smart Chain Testnet",
  "0x89": "Polygon Mainnet",
  "0x13881": "Polygon Mumbai Testnet",
  "0x66": "Harmony Mainnet",
  "0x67": "Harmony Testnet",
  "0xA4B1": "Arbitrum Mainnet",
  "0xA4B0": "Arbitrum Testnet",
  "0xA86": "Avalanche Mainnet",
  "0xA85": "Fuji C-Chain (Avalanche Testnet)",
  "0xFA": "Fantom Opera",
  "0xFA2": "Fantom Testnet",
  "0x64": "xDai",
  "0x4D": "Sokol (xDai Testnet)",
  "0x1A4D2": "GoChain Mainnet",
  "0x7A69": "Local Development Network (Hardhat Network)",
  "0xe708": "Linea Mainnet",
  "0x539": "Ganache Local",
};
export const RCP_PROVIDER = process.env.REACT_APP_RCP_PROVIDER;
export const SENDER_PRIVATE_KEY = process.env.REACT_APP_SENDER_PRIVATE_KEY;
